Progressing on CPA NGX Data-Access services.
TamuGeoInnovation/Tamu.GeoInnovation.js.monorepo pull request #185
Opened 2022-02-05 04:10 UTC by IsaiahV98

2022-02-22 01:14 UTC, Proantagonist commented
Discussion:

If we can write tests with any random input values, endpoint urls, etc, and mock any kind of response, and make assertions that effectively are `true == true`, then what is the value of these tests. I have a really hard time understanding why we should dedicate any amount of time to these tests except for maybe coverage reporting.

2022-02-22 01:14 UTC, Proantagonist requested changes

2022-02-22 01:14 UTC, Proantagonist commented on libs/cpa/ngx/data-access/src/lib/services/response/response.service.spec.ts
> +    ];
Incorrect input and return type. I realize the service method being tested doesn't have a very useful implicit return type, but you are encouraged to look at the implementation and determine what kind of response comes back, if any, and have more accurate tests.

2022-02-22 01:14 UTC, Proantagonist commented on libs/cpa/ngx/data-access/src/lib/services/scenario/scenario.service.spec.ts
> +    });
Incorrect return type and incorrect assertion

2022-02-22 01:14 UTC, Proantagonist commented on libs/cpa/ngx/data-access/src/lib/services/scenario/scenario.service.spec.ts
> +    const req = httpTestingController.expectOne(`${'Fooscenarios'}`);
This is definitely not the endpoint

2022-02-22 01:14 UTC, Proantagonist commented on libs/cpa/ngx/data-access/src/lib/services/snapshot/snapshot.service.spec.ts
> +    });
Invalid return type and assertion

2022-02-22 01:14 UTC, Proantagonist commented on libs/cpa/ngx/data-access/src/lib/services/workshop/workshop.service.spec.ts
> +    });
Incorrect return type and assertion

2022-02-25 18:32 UTC, IsaiahV98 commented on libs/cpa/ngx/data-access/src/lib/services/participant/participants.service.spec.ts
> +const spyEnvironment = {
Jest as a testing library makes no real distinction between spys and mocks (both result in mock functions): https://jestjs.io/docs/jest-object#jestspyonobject-methodname

2022-02-25 18:34 UTC, IsaiahV98 commented
> Discussion:
> 
> If we can write tests with any random input values, endpoint urls, etc, and mock any kind of response, and make assertions that effectively are `true == true`, then what is the value of these tests. I have a really hard time understanding why we should dedicate any amount of time to these tests except for maybe coverage reporting.

The value in these tests came from me attempting to figure how to deal with angular service dependencies utilizing Jest. Identifying and documenting the correct way deal with scenarios in which a service is dependent on another service, and identifying and documenting the correct way to deal with scenarios in which a service is dependent on Angular’s  HttpClient via the utilization of the HttpClientTestingModule and HttpTestingController. The files and corresponding functions under test here have their logic completely dependent on dependencies, which means to my understanding that there is basically nothing to test for in the scope of a unit test. So, for future testing there is no point outside of increasing testing coverage for unit testing these kinds of files/functions. 

However, now that it is documented how to properly utilize HttpClientTestingModule and HttpTestingController, we can in the future refer back to this documentation and code example for scenarios in which logic is not completely dependent on dependencies. Such as pipe calls on HttpClient requests and such.

2022-02-25 18:35 UTC, IsaiahV98 commented on libs/cpa/ngx/data-access/src/lib/services/participant/participants.service.spec.ts
> +    ];
> This is also where my understanding of the purpose of these tests falls apart. The dummyResponse is the incorrect return type for the service call createParticipantForWorkshop. The service method returns an object representing a participant, not an array of participants which is what you're testing for.

This is something I should have payed closer attention to, and will work on fixing.

2022-04-07 16:53 UTC, IsaiahV98 commented on libs/cpa/ngx/data-access/src/lib/services/participant/participants.service.spec.ts
> +  it('createParticipantForWorkshop()', () => {
Fixed

2022-04-07 17:03 UTC, IsaiahV98 commented on libs/cpa/ngx/data-access/src/lib/services/participant/participants.service.spec.ts
> +    expect(req.request.method).toEqual('POST');
Works, and applied for all tests.

2022-07-06 01:45 UTC, merged