Unit testing
TamuGeoInnovation/Tamu.GeoInnovation.js.monorepo pull request #53
Opened 2020-06-24 01:23 UTC by IsaiahV98

2020-07-08 01:34 UTC, IsaiahV98 commented
## Focus: NestJS/TypeORM Unit Testing 
Initially I utilized the following guide: [“_Unit Testing with NestJS and Jest: A comprehensive tutorial_” by jackallcock97](https://medium.com/@jackallcock97/unit-testing-with-nestjs-and-jest-a-comprehensive-tutorial-464910f6c6ba).
### Highlights: ###
- Test a Controller by mocking the services via  jest.mock("../.../foobar.service"); after each import. 
`jest.mock("../client/client.service");`
- Test a service by mocking the repositories via the use of custom mocks. 
```// @ts-ignore 
export const repositoryMockFactory: () => MockType<Repository<any>> = jest.fn(() => ({
 findOne: jest.fn(),
 find: jest.fn(),
 update: jest.fn(),
 save: jest.fn()
}));export type MockType<T> = {
 [P in keyof T]: jest.Mock<{}>;
};
```

### Concerns: ### 
- Introduction of clutter via custom mocks.

- High possibility of accidentally introducing [Implementation testing](https://kentcdodds.com/blog/testing-implementation-details).

These concerns lead me to seeking out other resource for information, which led me to find the work of Jay McDoniel on [Stack Overflow](https://stackoverflow.com/questions/57099863/spyon-typeorm-repository-to-change-the-return-value-for-unit-testing-nestjs
) and [GitHub](https://github.com/jmcdo29/testing-nestjs).

### Highlights: ####
- Cleaner implementation of Unit Testing for Services without the need of custom mocks. 

- Provided detailed examples of both strictly Unit Testing, and Integration Testing. 


While there still remains a decent amount of logic without coverage in the Covid Data-Api folder, the plan is to cover these functions in the future with [Integration Testing](https://github.com/rostgoat/testing-nestjs/blob/9dbc1a4810ce0ecffc2399eaaf2b7cdee03b89db/apps/typeorm-sample/src/cat/cat.integration.spec.ts
) to avoid writing Unit Tests that are implementation dependent. 


### Other Notes: ###  
I have chosen to wrap every instance of testing a specific logical function call in a **Describe** statement, with **It** statements for every logical return case inside. This allows for clearer reading of both the file, and the output from Jest. 
```
  describe('getWebsitesForCounty', () => {
    it('should return expectedResult', async () => {
      const mockParameter = 'undefined';
      const expectedResult = {
        status: 400,
        success: false,
        message: 'Invalid county fips'
      };
      expect(await websitesService.getWebsitesForCounty(mockParameter)).toMatchObject(expectedResult);
    });
    it('should return expectedResult', async () => {
      const mockParameter = undefined;
      const expectedResult = {
        status: 400,
        success: false,
        message: 'Invalid county fips'
      };
      expect(await websitesService.getWebsitesForCounty(mockParameter)).toMatchObject(expectedResult);
    });
    it('should return expectedResult', async () => {
      const mockParameter = 0;
      const expectedResult = {
        status: 400,
        success: false,
        message: 'Invalid county fips'
      };
      expect(await websitesService.getWebsitesForCounty(mockParameter)).toMatchObject(expectedResult);
    });
  });
```

2020-09-04 22:19 UTC, Proantagonist requested changes
Overall solid PR.

Only minor changes in this one. 

For future PR's, or passes keep in mind that form components (input, texbox, etc) need to test interoperability with form controls for use in reactive forms. This is their main intended use case.

In terms of style, keep it consistent and let things breathe. Makes it easier to read. 

```
  it('should correctly evaluate registerOnChange', () => {
    component.registerOnChange(component.writeValue(true));
    expect(component.value).toBeTruthy();
  });
  it('should correctly evaluate registerOnTouched', () => {
    component.registerOnTouched(component.writeValue(true));
    expect(component.value).toBeTruthy();
  });
  it('should correctly evaluate setDisabledState', () => {
    component.setDisabledState(true);
    expect(component.disabled).toBeTruthy();
  });
```

Adding a space between each of those cases increases readability.

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/ui-kits/ngx/layout/src/lib/components/accordion/accordion.component.spec.ts
> +/*@Component({
Removed

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/base/base.service.spec.ts
> +  });*/
Removed

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/counties/counties.service.spec.ts
> +  });*/
Removed

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/county-claims/county-claims.service.spec.ts
> +    });*/
Removed

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/field-categories/field-categories.service.spec.ts
> +    });
Removed

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/field-categories/field-categories.service.spec.ts
> +    });
Removed

2020-09-21 16:06 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/field-categories/field-categories.service.spec.ts
> +    });*/
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/phone-numbers/phone-numbers.service.spec.ts
> +    });*/
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/states/states.service.spec.ts
> +    });*/
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/states/states.service.spec.ts
> +    });*/
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/testing-sites/testing-sites.service.spec.ts
> +  });
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/users/users.service.spec.ts
> +  */
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/users/users.service.spec.ts
> +    });*/
Removed

2020-09-21 16:07 UTC, IsaiahV98 commented on libs/covid/data-api/src/lib/modules/users/users.service.spec.ts
> +    });*/
Removed

2020-09-21 17:06 UTC, IsaiahV98 commented on libs/ui-kits/ngx/forms/src/lib/components/checkbox-group/checkbox-group.component.spec.ts
> +import { QueryList } from '@angular/core';
Removed unused imports

2020-09-21 17:07 UTC, IsaiahV98 commented on libs/ui-kits/ngx/forms/src/lib/components/radio-group/radio-group.component.spec.ts
> +import { Angulartics2Module } from 'angulartics2';
Removed unused imports

2020-09-21 17:07 UTC, IsaiahV98 commented on libs/ui-kits/ngx/layout/src/lib/components/accordion/accordion-header/accordion-header.component.spec.ts
> +import { EventEmitter } from 'events';
Removed unused imports, and auto-imports

2020-09-21 17:08 UTC, IsaiahV98 commented on libs/ui-kits/ngx/navigation/mobile-tile/src/lib/components/tile-navigation/tile-navigation.component.spec.ts
> +import { Observable, of as observableOf } from 'rxjs';
Remove unused imports.

2020-09-21 17:10 UTC, IsaiahV98 commented on libs/ui-kits/ngx/navigation/mobile-tile/src/lib/components/tile-navigation/tile-navigation.component.spec.ts
> +import { Observable, of as observableOf } from 'rxjs';
Import statements correctly ordered

2020-09-21 17:24 UTC, IsaiahV98 commented on libs/ui-kits/ngx/navigation/mobile-tile/src/lib/components/tile-submenu/tile-submenu.component.spec.ts
> +    const yeet = spyOn(TileServiceStub, 'toggleSubmenu');
Fixed

2020-09-21 17:24 UTC, IsaiahV98 commented on libs/ui-kits/ngx/navigation/mobile-tile/src/lib/components/tile/tile.component.spec.ts
> +  });
Deleted

2020-09-21 17:26 UTC, IsaiahV98 commented on libs/ui-kits/ngx/navigation/mobile-tile/src/lib/services/tile.service.spec.ts
> +  });
Described behavior.

2020-09-21 17:33 UTC, IsaiahV98 commented on libs/ui-kits/ngx/layout/src/lib/abstracts/abstract-content-swap/abstract-content-replacer.component.spec.ts
> +    expect(component.toggleIndex).toEqual(8);
I believe this was something that I was meaning to get back to, but overlooked. Fixed now.

2020-09-23 17:13 UTC, IsaiahV98 commented on libs/ui-kits/ngx/layout/src/lib/components/accordion/services/accordion.service.spec.ts
> +  });
Fixed

2020-09-23 17:13 UTC, IsaiahV98 commented on libs/ui-kits/ngx/layout/src/lib/components/accordion/services/accordion.service.spec.ts
> +  });
Checked emitted values

2020-09-23 18:37 UTC, Proantagonist commented on libs/ui-kits/ngx/layout/src/lib/components/accordion/services/accordion.service.spec.ts
> +  });
👍

2020-10-02 20:33 UTC, closed without merging